### ISSUE TITLE
counsel-projectile-rg uses fuzzy matching

### ISSUE THREAD

**Issue by Opioid** [ericdanan/counsel-projectile#113]
Recently I noticed counsel-projectile-rg uses fuzzy matching for me. I don't think it always used to be this way, because it is useless in larger projects.

I added this to my config file, but it doesn't change the counsel-projectile-rg behavior:
```
  (setq ivy-re-builders-alist
		'((swiper . ivy--regex-plus)
		  (counsel-rg . ivy--regex-plus)
                  (counsel-projectile-rg . ivy--regex-plus)
		  (t      . ivy--regex-fuzzy)))
```
Can this be configured another way?

**Comment by ericdanan** [comment]
Probably related to counsel itself and not counsel-projectile, because `counsel-projectile-rg` relies on `counsel-rg` and so should use the same matching. Try calling the latter command to confirm.

`counsel-rg` itself calls `counsel-ag`, so the three commands will always use the same matching and to modify it, you should replace `counsel-rg` with `counsel-ag` in your `ivy-re-builders-alist` config (and you can drop the `counsel-projectile-rg` line).

**Comment by Opioid** [comment]
The advice with `counsel-ag` solved my problem!
