### ISSUE TITLE
counsel-projectile-find-file ignoring some .projectile file

### ISSUE THREAD

**Issue by Opioid** [ericdanan/counsel-projectile#114]
I have a project where I successfully excluded certain directories from counsel-projectile-find-file via .projectile. 
When trying the same thing in a different (much larger) project, it seems to fail. I know that this is not much to go on, but does this sound familiar in some way? What could this depend on?

EDIT: One difference is, that the failing project is not a git repository. While editing a file I was also spammed with messages telling me, that the TAGS file of a completely different project is missing. The Modeline does display the "correct" projectile marker, though.

**Comment by ericdanan** [comment]
It doesn't sound familiar, and likely to come from projectile itself rather than counsel-projectile (`counsel-projectile-find-file` should show the same files as `projectile-find-file`). So I'd suggest you update projectile, clear the failing project's cache and call `projectile-find-file`. If it still fails, perhaps this comes from your indexing method, check `projectile-indexing-method` (there have been changes in this variable recently, the indexing methods got renamed).

**Comment by Opioid** [comment]
I think you are right, and this is a projectile question. I will post it there instead.
