### ISSUE TITLE
counsel-projectile-find-file: buffer opening in other window

### ISSUE THREAD

**Issue by manuel-uberti** [ericdanan/counsel-projectile#116]
Hi,

this is what I am trying to do:

- in a Git-versioned project, I use `counsel-projectile-find-file`
- since it does not show files/directories listed in `.gitignore`, I hit <kbd>C-x C-f</kbd>, which in my case is bounded to `counsel-find-file`
- on the candidate I am looking for, I press <kbd>RET</kbd> (`ivy-alt-done`)

The resulting buffer is opened in a new window instead of the current one.

This is only happening when using `counsel-find-file` from `counsel-projectile-find-file`. Otherwise, `counsel-find-file` works as expected.

I am using latest `counsel-projectile` and `ivy/counsel` from MELPA. These are some details on my system in case you need them:

```
GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2018-12-19

Repository revision: 70926a3e8671034fd5cb1a546f9c107feda729a3
Configured using:
--host=x86_64-debian-linux-gnu --with-modules

Emacs uptime: 1 hour, 33 minutes, 11 seconds
Default font: Iosevka SS08
Colour theme: sanityinc-tomorrow-night
Operating system: Ubuntu 18.04.1 LTS
Window system: x11
Desktop environment: GNOME Shell 3.28.3
```

**Comment by ericdanan** [comment]
Counsel projectile has a built-in mechanism to do what you want: instead of hitting `C-x C-f`, hit `M-o m`. That will close the minibuffer completion session and call `counsel-find-file` from the project root. Then the file you select should be opened in the same buffer by default (or another buffer with `M-o j`). This is available from most counsel projectile commands, not only `counsel-projectile-find-file`.

**Comment by manuel-uberti** [comment]
Works like a charm. Thank you!
