### ISSUE TITLE
counsel-projectile-ag is not actually narrowing results

### ISSUE THREAD

**Issue by paulbdavis** [ericdanan/counsel-projectile#121]
Since the update to `ivy` and `counsel` 0.11.0 and `counsel-projectile` 0.3.0, the results for `counsel-projectile-ag` are not being narrowed.

Instead of only matching lines showing up, every line from every file in the project is there.

This issue does not occur when using `counsel-projectile-git-grep`, the results filter down as usual.

**Comment by ericdanan** [comment]
I can't reproduce your issue. Does it also occur if you call `counsel-ag` instead of `counsel-projectile-ag`?

**Comment by paulbdavis** [comment]
It *does*. Seems like an issue with `ivy` then (or `ag`?)

**Comment by ericdanan** [comment]
It is probably not an issue with counsel-projectile then (`counsel-projectile-ag` essentially relies on `counsel-ag` for the completion).

If you didn't have this issue with the previous ivy / counsel version, then it must come from ivy / counsel. Perhaps you have some custom settings for these packages that cause the issue with the new version. If you already had the issue with the previous ivy / counsel version, you could try calling ag directly from a shell to see if the problem is with ag itself (you could try if updating ag fixes it).

**Comment by ericdanan** [comment]
Saw the issue was fixed for `counsel-ag`:

abo-abo/swiper/issues/1907

I suppose this also fixes it for `counsel-projectile-ag`, right?

**Comment by paulbdavis** [comment]
Yes, this is fixed. Until the next version is tagged there is a workaround posted in that issue thread.
