### ISSUE TITLE
Performance of counsel-projectile-switch-project

### ISSUE THREAD

**Issue by swarnendubiswas** [ericdanan/counsel-projectile#124]
I am facing performance issues with `counsel-projectile-switch-project` compared to `projectile-switch-project` and I am trying to understand what is wrong. The other "performance" issues reported do not seem to solve the problem. Here is a MWE which works for me. 

```
(require 'package)
(setq package-user-dir (expand-file-name "~/.emacs.d/elpa/")
      package-enable-at-startup nil)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))

(defcustom dotemacs-temp-directory (concat user-emacs-directory "tmp/")
  "Storage location for various configuration files."
  :group 'dotemacs)

(use-package projectile
  :ensure t
  :config
  (setq projectile-known-projects-file (concat dotemacs-temp-directory "projectile-known-projects.eld")
        projectile-cache-file (concat dotemacs-temp-directory "projectile.cache"))
  (projectile-mode 1) ; Otherwise keybindings not bound explicitly with bind* will not be respected
  (setq projectile-enable-caching t
        projectile-file-exists-remote-cache-expire nil
        projectile-verbose nil
        projectile-require-project-root t ; Use projectile only in desired directories, too much noise otherwise
        projectile-find-dir-includes-top-level t
        projectile-switch-project-action 'projectile-find-file ; Use projectile-dired to view in dired
        ;; projectile-mode-line nil
        projectile-completion-system 'ivy
        ;; The contents of .projectile are ignored when using the alien project indexing method
        projectile-indexing-method 'hybrid
        projectile-enable-idle-timer t ; Runs "regenerate ctags" by default
        projectile-idle-timer-seconds 120
        projectile-project-search-path '("xxx" "yyy" "zzz"))

  (add-to-list 'projectile-ignored-projects `,(concat (getenv "HOME") "/")) ; Do not consider the home dir as a project

  (dolist (dirs '(".cache"
                  ".dropbox"
                  ".git"
                  ".hg"
                  ".svn"
                  ".nx"
                  "elpa"
                  "auto"
                  "__pycache__"
                  ".vscode"))
    (add-to-list 'projectile-globally-ignored-directories dirs))

  (dolist (item '("GPATH"
                  "GRTAGS"
                  "GTAGS"
                  "GSYMS"
                  "TAGS"
                  ".tags"
                  "__init__.py"))
    (add-to-list 'projectile-globally-ignored-files item))

  (dolist (list '("\\.out$"
                  "\\.pdf$"
                  "\\.pyc$"
                  "\\.rel$"
                  "\\.rip$"
                  "~$"))
    (add-to-list 'projectile-globally-ignored-file-suffixes list))

  ;; ;; https://www.reddit.com/r/emacs/comments/320cvb/projectile_slows_tramp_mode_to_a_crawl_is_there_a/
  ;; (defadvice projectile-project-root (around ignore-remote first activate)
  ;;   (unless (file-remote-p default-directory) ad-do-it))

  (add-hook 'projectile-after-switch-project-hook
            (lambda ()
              (unless (bound-and-true-p treemacs-mode)
                (treemacs)
                (other-window 1))))

  (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map))

(use-package counsel-projectile
  :ensure t
  :config
  (counsel-projectile-mode)
  ;; Sort projects from newest to oldest
  (add-to-list 'ivy-sort-functions-alist
               '(counsel-projectile-switch-project . file-newer-than-file-p))
  :bind (("<f5>" . counsel-projectile-switch-project)
         ("<f6>" . counsel-projectile)
         ("<f7>" . counsel-projectile-rg)))
```

1) Start Emacs with `emacs -Q`
2) Open the file and eval the buffer
3) Invoke `projectile-switch-project` in one run, and `counsel-projectile-switch-project` in the other. The second run takes >5 seconds for my setup, while the first is ~1s. 

Is there an issue with my setup or can this be a bug with `counsel-projectile`?

**Comment by ericdanan** [comment]
Are you talking about the time it takes to show the list of projects to switch to or the time it takes to switch to the selected project? Anyway, for me there is no noticeable difference between `projectile-switch-project` and `projectile-switch-project`. Perhaps you could try commenting out different portions (or all) of your config code to isolate where the problem comes from. Look at your config code, the only thing I see that seems to apply to `counsel-projectile-switch-project` but not `projectile-switch-project` is the added entry in `ivy-sort-functions-alilst`, so I would look at that first (perhaps you have remote projects and it takes some time to get the date/time?).

**Comment by swarnendubiswas** [comment]
I am talking about the time it takes to show the list of projects. 

Commenting out the sorting does not help improve the performance, in fact other `counsel-projectile` commands like `rg` are also slow to start. I checked `projectile.cache` and `projectile-known-projects.eld` and they all contain local information.

**Comment by ericdanan** [comment]
I can't reproduce the issue. A few questions:
- Do the counsel-projectile functions remain slow when you call them again or is it only on the first call?
- Did you update projectile, ivy/counsel, and counsel-projectile to the latest versions?
- What happens with `emacs -Q` and commenting out all your `:config` code for projectile and counsel-projectile?

**Comment by swarnendubiswas** [comment]
- It is slow only on the first call. 
- Yes, all the packages are the latest.
- Good idea, I should have tried this. Surprisingly, it seems commenting out the `:bind` in `counsel-projectile` improves performance. By that I mean, `counsel-project-switch-project` performs similarly with `projectile-switch-project`.

**Comment by ericdanan** [comment]
From the use-package readme, I see that the `:bind` keyword causes package loading to be deferred. Since you use this keyword in the counsel-projectile form but no the projectile one, I guess that the latter is automatically loaded when you start emacs but not the former. And if the rest of your setup does not cause counsel and ivy to be automatically loaded either, these will also have to be loaded the first time you call a counsel-projectile command. That could explain why `projectile-XXX` is faster than `counsel-projectile-XXX` but only on the first call (although a 3-seconds difference seems a lot to me).

If that's indeed the cause, then you should be able to get rid of the difference by amending your use-package form for counsel-projectile as follows:

``` emacs-lisp
(use-package counsel-projectile
  :ensure t
  :config
  (counsel-projectile-mode)
  ;; Sort projects from newest to oldest
  (add-to-list 'ivy-sort-functions-alist
               '(counsel-projectile-switch-project . file-newer-than-file-p))
  (bind-keys ("<f5>" . counsel-projectile-switch-project)
             ("<f6>" . counsel-projectile)
	     ("<f7>" . counsel-projectile-rg)))
```

Then counsel-projectile (and its dependencies) should be automatically loaded when emacs starts, so `counsel-projectile-XXX` should be as fast as `projectile-XXX`. But of course your emacs startup time should increase as a consequence, so you should see what you prefer.

**Comment by swarnendubiswas** [comment]
Thanks for the suggestion. I will close the issue since I have an work around.

I load `ivy` and `counsel` on start up, and the load times are reasonable. So is with `projectile`. What is still unclear to me is why would only `counsel-projectile` incur this overhead.
