### ISSUE TITLE
add a counsel-projectile-ag function.

### ISSUE THREAD

**Issue by kain88-de** [ericdanan/counsel-projectile#13]
It would be nice to have function to also search with ag with the `projectile-ag` binding `C-c p s s`.  Something like this

``` elisp
(defun counsel-projectile-ag (&optional options)
  (interactive "P")
  (counsel-ag "" (projectile-project-root) ))
```

This works calling it with `M-x` but not when I bind it with  `(define-key projectile-command-map [remap projectile-ag] #'counsel-projectile-ag)`. I don't have a lot of elisp experience so I don't know what the problem is.

Also this is a great package. It makes switching from helm a lot easier

**Comment by ericdanan** [comment]
I looked into this and saw [here](https://github.com/bbatsov/helm-projectile/commit/3db706c9147a54a618bdb6e5de827d931d8ae9a6#comments) that remapping should be done in `projectile-mode-map` instead of `projectile-comamnd-map`. That is to say, you should bind the key with

```
(define-key projectile-mode-map [remap projectile-ag] #'counsel-projectile-ag)
```

Does this work?

This made me realize that it would be better if counsel-projectile also remapped the projectile keys, so I just pushed a commit that implements this.

Thanks.

**Comment by kain88-de** [comment]
Yes this works. Thank you.

**Comment by ericdanan** [comment]
I just added a `counsel-projectile-ag` function, which is a little bit more sophisticated than yours in that it takes into account the projectile ignored files. I mostly copied it from `helm-projectile-ag`.

I also added the corresponding remapping in `counsel-projectile-toggle`, so you should be all set with `counsel-projectile-on`.

**Comment by kain88-de** [comment]
thanks
