### ISSUE TITLE
counsel-projectile-switch-project doesn't open same named files from other projects.

### ISSUE THREAD

**Issue by kain88-de** [ericdanan/counsel-projectile#14]
I have an issue switching between projects that have common filename like _README_, _CHANGELOG_, etc. The problem is that once I have a file called  `README.md` open in any project I will always go back to this buffer when I try to open any other `README.md` in another project.

For example I have 2 projects `foo` and `bar`. Both have a `README.md` file at their root. After I start emacs I first open `foo:README.md`. When I then use `counsel-projectile-switch-project` to open `bar:README.md` I will stay in the `foo:README.md` buffer.

This is annoying for me because I usually interact with a git-repository with magit and when I do some routine fetching and  updating from collaborator projects/branches I open the README of the project and then start magit.

**Comment by ericdanan** [comment]
I can reproduce this. I am a little bit short on time right now but will look at it ASAP. As a temporary workaround, instead of switching project with the default action (<kbd>RET</kbd> or <kbd>M-o o</kbd>) to open the readme and then open magit, perhaps you could switch with the action to open open magit (<kbd>M-o g</kbd>), and from there calling `counsel-projectile-find-file` or `counsel-projectile` to open the project readme should work.

**Comment by kain88-de** [comment]
Actually the `M-o g` shortcut is a very good work around for me, I think I will start using that more regularly.

**Comment by ericdanan** [comment]
I think it should work now, could you test? (make sure that ivy is up-to-date beforehands)

**Comment by kain88-de** [comment]
Yes it's fixed thanks.
