### ISSUE TITLE
counsel-projectile-rg doesn't work

### ISSUE THREAD

**Issue by arkhan3x** [ericdanan/counsel-projectile#140]
Cheers
I am having the problem that can be seen in the image when using counsel-projectile-rg

![img-2019-11-29-080952](https://user-images.githubusercontent.com/48631466/69871216-34d96e00-1280-11ea-8b98-ee08d746ef62.png)

I hope you can help me.

Thank you

**Comment by ericdanan** [comment]
Hello,

I am not able to reproduce the issue. Are counsel, projectile, and counsel-projectile up-to-date? What version or rg are you using? Did it work before and stopped at some point?

**Comment by arkhan** [comment]
hello @ericdanan,
I have the same problem, but the reason for this is my user's default shell [(https://xon.sh/)](https://xon.sh/).
I solved it as follows:
![img-2019-12-08-070604](https://user-images.githubusercontent.com/3141865/70389131-44943900-1989-11ea-8b4f-83f1f1885f38.png)
It works fine, but the problem is that you cannot add more parameters with C-u.
![img-2019-12-08-070754](https://user-images.githubusercontent.com/3141865/70389149-8c1ac500-1989-11ea-8ee0-f16b7e927892.png)
Since the command it executes is sh and not rg.

Thanks.

**Comment by ericdanan** [comment]
It would be best of course if it worked directly with rg. The problem is that I don't know why it doesn't work as I can't reproduce the issue. Can you try calling `counsel-rg` and tell me if you face the same problem? `counsel-projectile-rg` relies on `counsel-rg`, so that will tell us whether your issue is with counsel or counsel-projectile.

**Comment by arkhan3x** [comment]
I close this issue, because the problem is using a shell as xonsh by default and not in this package

Thanks
