### ISSUE TITLE
counsel-projectile-rg not ignoring git ignored files/directories

### ISSUE THREAD

**Issue by hisnawi** [ericdanan/counsel-projectile#147]
Recently I started noticing matched results in files that should be ignored by git.
In our project however, there are .gitignore files in different directory levels.
Does counsel-projectile-rg not take into account these files?

I confirmed that when "modifying" these files they don't show up in git as unstaged. So they are indeed not part of the project. Counsel-projectile-rg still list their matches.

I tried deadgrip and helm-projectile-rg and they both ignore these files.

**Comment by hisnawi** [comment]
It could also be possible that counsel-projectile-rg first checks the .gitignore files then apply .ignore file which overwrites some of the directories in .gitignore.
I think .projectile should be processed first then .gitignore gets processed next to overwrite any previous declaration.

Meaning, if in .ignoreI have:
!/x/y/z 
as not being ignored (because I care about some of the files in it being searched).
And .gitignore has:
/x/y/z/w
then what is in /z should be searched, but what is in /w should not.

**Comment by hisnawi** [comment]
i did also verify that executing "rg" command on the command prompt also doesn't show results in these ignored files. Which means the problem is for sure in counsel-projectile-rg

Another update is counsel-rg also doesn't show results in the ignored files.
It is only counsel-projectile-rg that has an issue.

**Comment by hisnawi** [comment]
I can also try to debug it if you could advise on where I could put debugging statements in the counsel-projectile-rg function that prints the full rg command used (along with ignored files used)

**Comment by hisnawi** [comment]
I am also able to recreate the issue with a sample small project. I can upload it on github if you want to take a look.

**Comment by ericdanan** [comment]
Thanks for reporting. Yes please upload a sample project so I can try to reproduce and investigate the issue.

**Comment by hisnawi** [comment]
Here you go:
`https://github.com/hisnawi/test`

If you go to:
`test/second/third/forth/a.c`
And from inside the file "counsel-projectile-rg" for q_file, it will show up in the results although from:
`test/second/.gitignore `
it should be ignored:
`"third/*/fifth/"`

"counsel-rg" correctly ignores it.

**Comment by ericdanan** [comment]
I am not able to reproduce the issue, `q_file` never shows up and in fact I don't see it anywhere in your test project. Where is it supposed to be?

**Comment by hisnawi** [comment]
sorry, a_file

**Comment by hisnawi** [comment]
Ok. because the directory <fifth> is ignored (through git) it was not uploaded to github.
Could you create a directory called fifth and in it have a file named q.c and write the line q_file 

so test/second/third/forth/fifth/q.c
which has one line: q_file 

From the file a.c searching for q_file should yield no results. Yet it does with counsel-projectile-rg

**Comment by ericdanan** [comment]
I did that but I get the result both with `counsel-projectile-rg` and `counsel-rg`.  Are your `projectile` and `ivy` / `counsel` up to date? Which version of `rg` are you using?

**Comment by hisnawi** [comment]
I will get you this information shortly. But aside from that, getting the result is the wrong behavior isn’t it?

**Comment by hisnawi** [comment]
rg --version
ripgrep 11.0.2
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

 counsel            20200211.958   installed
 counsel-projectile 20200130.1029 dependency 
 ivy                20200211.1338 dependency 
 projectile         20200206.1749 dependency

**Comment by ericdanan** [comment]
OK, I was not testing properly (had copied rather than cloned your project). Now indeed `rg` and `counsel-rg` don't show any match, bur for me `counsel-projectile-rg` behaves similarly.

`counsel-projectile-rg` basically just calls `counsel-rg` from the project root and adding ignored files and directories from `projectile`. `counsel-rg` in turn calls `rg` from the git root (identified by the existence of a `.git/` directory) if it finds one or the current directory instead. So I don't see why they would not behave identically in your test project when called from `/second/third/forth/a.c`. Could you try again `counsel-projectile-rg` from that file, perhaps with a `C-u` prefix to invalidate the cache? Could you also make sure the project root is identified correctly by calling `projectile-project-root` from that file?

**Comment by hisnawi** [comment]
Ok. there is more to the story that I didnot think it was related. But ended up being very related.
I think there is a conflict between what the .projectile file contains and the ignored git files.
Bare with me.

In the test directory create an empty directory called "mainproj" and move all files under "test" into "mainproj".
In "test" now create a file ".projectile" with the content:
-/mainproj/
+/second/third

Now when you go to the a.c file, searching for anything using counsel-projectile-rg returns error. while searching with counsel-rg returns some results (search for just a_file, it doesnt have to be the ignored file q_file, that would actually get ignored correctly).
Also searching with helm-projectile-rg returns results.

I think the reason counsel-projectile-rg returns error_code is related to the reason in my local project I see results from ignored git files. There could be confusion between what .projectile includes and what rg needs to ignore.

My understanding is .projectile include paths to be searched when looking for files by name, but not as part of rg search targets.

**Comment by ericdanan** [comment]
I need some clarification:

> move all files under "test" into "mainproj".

Do you mean also move the `.git` folder?

Also, in your test project the `.projectile` file is empty so how could this explain why you see a difference between `counsel-projectile-rg` and `counsel-rg` there?

**Comment by hisnawi** [comment]
Apologies for not getting back to you sooner.
Please download and unzip the file:
https://github.com/hisnawi/test/blob/master/test.zip

I had to zip it since uploading it wont upload all the "ignored" files.

Now if you search for anything from any file there will be an "error code 2".
Running regular rg command, helm-projectile-rg or counsel-rg all yield results.

Once we figure out this issue then we can look at the main issue of this thread.

thanks for your patience.

**Comment by ericdanan** [comment]
I also get this error but it seems to be simply because the `mainproj` directory in your `.projectile` file does not exist. I suppose you renamed it to `maindir`. If I change the two instances of `mainproj` to `maindir` in your `.projectile` file, the error disappears. The other commands you tried show no error because they don't parse the `.projectile` file.

**Comment by hisnawi** [comment]
Thanks for catching that.
So after fixing this in the .projectile file (mainproj -> maindir).
In the "a.c" file search for q_file
Based on the git rules it should show no results. Yet it does with counsel-projectile-rg.

**Comment by ericdanan** [comment]
OK I think I understand the problem. `counsel-projectile-rg` parses the `.projectile` file and passes the paths to the kept directories (those with a `+` in the `.projectile` file) to `rg`, `rg` being called from the project root. But as per the `rg` man page:

> Paths specified explicitly on the command line override glob and ignore rules.

So `rg` does not parse the `.gitignore` files then. You can see the difference by running the two following commands:

- From `test/maindir/second/third/`, calling `rg q_file` gives no result
- From `test/` calling `rg q_file maindir/second/third` gives a result

But I'm not sure how to fix this. In your example it would probably work to call `rg` from the kept directory rather than passing its path to `rg` called from the project root. But in general there can be more than one kept directory so that approach isn't feasible. The best would perhpas to do the same as `projectile-ripgrep` or `helm-projectile-rg`: simply disregard the `.projectile` file. I'll have to think about it some more.

**Comment by hisnawi** [comment]
Thanks for looking into this. I agree. More consistent functionality as projectile-ripgrep is more desirable.

**Comment by hisnawi** [comment]
I take that back. If you ignore .projectile then how is counsel-projectile-rg is going to be any different from counsel-rg?

**Comment by ericdanan** [comment]
They would still be different because:
1. `counsel-projectile-rg` calls `rg` from the project root, whereas `counsel-rg` calls `rg` from the `git` root if it finds one and the current directory otherwise.
2. `counsel-projectile-rg` ignores files and directories specified by the variables `projectile--globally-ignored-file-suffixes-glob`, `projectile-ignored-files-rel`, and `projectile-ignored-directories-rel`.

**Comment by hisnawi** [comment]
Got it. 
I guess it is best to simply ignore the .projectile file then. Simply because .ignore can also be used (along with .gitignore) to specify which directories to ignore.

**Comment by hisnawi** [comment]
Any updates on this issue @ericdanan ?

**Comment by ericdanan** [comment]
Hello, sorry for not being reactive, I plan to do it but difficult to find the time currently.

**Comment by ericdanan** [comment]
Done, please test.

**Comment by hisnawi** [comment]
Hmm...it is not showing any results at all now.
I mean if you go to my same example from above and look for any text in any file using counsel-projectile-rg you get no results at all.

**Comment by ericdanan** [comment]
Well I can't reproduce your behavior now, I do get result in your above example searching for `file` from various places. Can you provide a specific search for which `counsel-projectile-rg` misses results for you?

**Comment by hisnawi** [comment]
I have gone as far as removing elpa directory and starting from scratch.
Executing counsel-projectile-rg yields no results for me.
I also used this very basic setup:
```
  (use-package counsel-projectile
    :ensure t
    )

```
Still no results.

This is the version I have:
counsel-projectile-20200430.2133
counsel-20200501.1508
projectile-20200427.1153

**Comment by ericdanan** [comment]
Can you tell me what do you search and from which file, and what does `counsel-rg` yield?

**Comment by hisnawi** [comment]
counsel-rg works:

![image](https://user-images.githubusercontent.com/8878871/80837340-7792cf80-8bab-11ea-9ead-c796925d2fe1.png)

But counsel-projectile-rg doesn't:
![image](https://user-images.githubusercontent.com/8878871/80837384-88dbdc00-8bab-11ea-9bdc-f3a780053a96.png)

**Comment by ericdanan** [comment]
Sorry, I had downloaded your `zip` file again and forgotten I needed to substitute `mainproj -> maindir` in the `.projectile` file. Now I get the same behavior as you searching for `test1` from the `test1.c` file.

But it actually seems to me to be the expected behavior from `counsel-projectile-rg`. As mentioned in my [comment above](https://github.com/ericdanan/counsel-projectile/issues/147#issuecomment-594919769), `counsel-projectile-rg` unlike `counsel-rg` takes into account ignored directories from `projectile-ignored-directories-rel`, in the present case it sees that you excluded the directory `maindir` in the `.projectile` file and so ignores everything in there (but it doesn't go as far as restricting attention to `maindir/second/third` as specified in the `.projectile` file because that would prevent it from excluding anything as discussed above).

**Comment by hisnawi** [comment]
I will look into this closer. But this is what I think:
1. I originally had both counsel-projectile-rg and helm-projectile-rg yeild same results.
2. Some of the git ignore files moved in my project from root directory to some sub directories. This broke counsel-projectile-rg but not helm-projectile-rg.
3. At some point we concluded that counsel-projectile-rg needs to do the same (I need to revise what same here means).
4. You fixed it, but now it doesn't show any results. However, helm-projectile-rg still shows the same results as before.

![image](https://user-images.githubusercontent.com/8878871/80871931-948ad980-8c63-11ea-9d52-f8203b4b433d.png)

You say councel-projectile-rg is doing the right thing. So now I am confused.

**Comment by ericdanan** [comment]
Well `counsel-projectile-rg` seems to me to be doing the right thing in your example project because you excluded the `/maindir/test1.c` file in your `.projectile` file and hence I assume you don't want to see results from that file when searching the project. I would say that ideally `counsel-projectile-rg` would also honor the `+` lines in the `.projectile` file, but we found out this forces it to discard all forms of exclusions (at least when there more than one such line), which I think is worse, hence the decision not to honor those lines.

I agree that consistency between various projectile UI (counsel-projectile, helm-projectile...) and plain projectile is also desirable. Now `projectile-ripgrep` basically calls `rg` from the project root and honors globally ignored files and directories but not project-specific ones, whereas `helm-projectile-rg` seems to simply call `rg` from the project root without worrying about any ignores. So the two will behave differently in some projects. `projectile-ag`, on the other hand, calls `ag` from the project root and respects both global and project-specific ignores as well as globally ignored file suffixes, whereas `helm-projectile-ag` seems to overlook globally ignored file suffixes but parse the `+` lines in the `.projectile` file (I'm not sure about this last point). I don't know the reasons behind these differences, but I'm not sure it will make things better to deliberately overlook some ignores we could handle in order to exactly mirror the plain projectile commands. I'll give it more thought though.

**Comment by hisnawi** [comment]
Ok. So I agree:
1. counsel-projectile-rg doesn't need to be consistent with other tools.
2. That files under maindir need to be ignored.

But I am not sure i agree with ignoring other files under +.
In maindir project example, trying to search from inside "third" directory which was declared + in the .projectile file is not yielding any results.
![image](https://user-images.githubusercontent.com/8878871/81022724-360c5980-8e23-11ea-969b-12776499a717.png)

I am not sure then how should be the flow?
How should .projectile be structure in a way that I could achieve:
1. Excluding everything under maindir
2. ignoring all .gitignore files as in maindir/second/.gitignore
3. Include files under maindir/second/third (other from the ones ignored from above).

**Comment by ericdanan** [comment]
`rg` fully supports `.gitignore` files, so one solution would be to ignore everything excepte `/maindir/second/third` there. But I guess you don't want that, so indeed you need add exclusions to your `.projectile` file. I think the `-/maindir` file in your `.projectile` file is redundant because the `+/maindir/second/third` means exclude everything except this directory. If you call `projectile-find-file` and your `projectile-indexing-method` is either `hybrid` or `native` then you should see only `/maindir/second/third/g.c` and `/maindir/second/third/forth/g.c`, which is what you want I think.

Now if I understand correctly, the goal is to have `projectile-rg` behave similarly, that is search only in these two files. I think unfortunately neither `projectile-rg` nor `helm-projectile-rg` not `counsel-projectile-rg` will give you this currently, because none of these commands parses the `+` lines in the `.projectile` file. There doesn't seem to be an easy solution to this because as we saw above, we can't simply pass the `+` paths to `rg` and simultaneously pass ignore patterns to it. I suppose one would instead need to call `rg` separately in each of the `+` directories, but it's not clear to me how to implement this with ivy.

**Comment by hisnawi** [comment]
Okay I am happy with this. Once I removed the redundant -(project) in the first line of my .projectile file things worked as expected.
My only problem now, which is not yours (this is just FYI, but happy to get any pointers :) )
Is I wanted to customize a function to list matching results in the first two levels if directory starting from the current one I am calling the function from. This is helpful to me since I work on a project which have multiple independent modules, so seeing the matching results for the module I am in come up first is very desirable.
This function used to work before your last change and now it doesn't.
As I get this error:
`ra/counsel-projectile-rg: Symbol’s function definition is void: counsel-projectile--string-trim-right [2 times]
`

This is the code:

```
    ;;;;;;;;;;;;;;;;;;;;;;;;;ra/counsel-projectile-rg;;;;;;;;;;;;;;;;;;;;;;;;
    ;;https://www.reddit.com/r/emacs/comments/etxdnl/sort_ripgrep_results_based_on_proximity_to/
    (defun ra/counsel--rg-targets ()
      (let ((files (split-string
                    (shell-command-to-string
                     (concat "~/.emacs.d/rg_smart_listfiles.sh"
                             " \"" (projectile-project-root) "\" "
                             " \"" (file-name-directory (directory-file-name default-directory)) "\" "
                             " \"" default-directory "\" "
                             " \"" (buffer-file-name) "\" "
                             ))
                    "\n" t nil)))
        (concat " " (mapconcat #'shell-quote-argument (delq t files) " ")))
      )

      ;;;###autoload
    (defun ra/counsel-rg (&optional initial-input initial-directory extra-rg-args rg-prompt)
      (interactive)
      (let ((counsel-ag-base-command
             (concat counsel-rg-base-command (ra/counsel--rg-targets)))
            (counsel--grep-tool-look-around
             (let ((rg (car (split-string counsel-rg-base-command)))
                   (switch "--pcre2"))
               (and (eq 0 (call-process rg nil nil nil switch "--version"))
                    switch))))
        (counsel-ag initial-input initial-directory extra-rg-args rg-prompt
                    :caller 'counsel-rg)))
      ;;;###autoload
    (defun ra/counsel-projectile-rg (&optional options)
      (interactive)
      (if (and (eq projectile-require-project-root 'prompt)
               (not (projectile-project-p)))
          (counsel-projectile-rg-action-switch-project)
        (let* ((ivy--actions-list (copy-sequence ivy--actions-list))
               (path
                (mapconcat 'shell-quote-argument
                           (or (projectile-normalise-paths
                                (car (projectile-parse-dirconfig-file)))
                               '("."))
                           " "))
               (ignored
                (mapconcat (lambda (i)
                             (concat "--glob !" (shell-quote-argument i)))
                           (append
                            (list
                             ;;(string-remove-prefix (projectile-project-root) (buffer-file-name))
                             ;;(string-remove-prefix (projectile-project-root) default-directory)
                             (string-remove-prefix (projectile-project-root)
                                                   (file-name-directory (directory-file-name default-directory)))
                             )
                            (projectile--globally-ignored-file-suffixes-glob)
                            (projectile-ignored-files-rel)
                            (projectile-ignored-directories-rel))
                           " "))
               (counsel-rg-base-command
                (format (counsel-projectile--string-trim-right counsel-rg-base-command " \\.")
                        (concat ignored " %s " path)))
               )
          (ivy-add-actions
           'counsel-rg
           counsel-projectile-rg-extra-actions)
          ;;(message "%s" counsel-rg-base-command)
          (ra/counsel-rg (eval counsel-projectile-rg-initial-input)
                         (projectile-project-root)
                         options
                         (projectile-prepend-project-name
                          (concat (car (split-string counsel-rg-base-command)) ": "))))))

```

**Comment by ericdanan** [comment]
I removed the function `counsel-projectile--string-trim-right` in the commit that fixed this issue because it was no longer needed. I suppose it would work for you again if you started from the new `counsel-projectile-rg` function  and amended it as you did above. Perhaps an alternative (and more robust) approach could be to add an entry for `counsel-projectile-rg` in `ivy-sort-functions-alist`.

**Comment by hisnawi** [comment]
Thanks for the help on this issue. Much appreciated.

**Comment by hisnawi** [comment]
I read more about `ivy-sort-functions-alist` but I couldn't find an option to sort by proximity to current file.

Only thing I found searching online is something like:
`(add-to-list 'ivy-sort-functions-alist '(counsel-projectile-rg . file-newer-than-file-p))`

But that would sort by newer files.
