### ISSUE TITLE
counsel-projectile-rg doesn't work if the dired-mode is on

### ISSUE THREAD

**Issue by templateK** [ericdanan/counsel-projectile#161]
On the `dired-mode`, The call `counsel-projectile-rg` from the child directory which has
depth greater than zero from the project root will fail.

For example, if the `dired-mode` cursor is on file path `project_root/some/path/in/between/Foo.txt`,
then the rg command is like this.

```
rg <pattern> Foo.txt
```

`counsel-rg` strips off the path prefix and uses just the file name under `dired-mode` cursor
or multiple marked files. the rg run right under the project root because rg process uses
default-directory which set by `counsel-projectile-rg` `initial-directory` parameter.
Apparently,the project root has no `Foo.txt` so it fails.

**Comment by templateK** [comment]
Will this issue be addressed? @ericdanan

**Comment by ericdanan** [comment]
Sorry for not replying, not finding much time at the moment. I can reproduce the issue when there are marked files in a dired buffer. It happens because `counsel-rg` relies on `counsel--rg-targets` to modify the rg comand when called from a dired buffer. I'll try to find a fix although there does not seem to be a trivial way to disable this behavior of `counsel-rg`.

**Comment by templateK** [comment]
stale activity. closing issue.
