### ISSUE TITLE
counsel-projectile-ag not working

### ISSUE THREAD

**Issue by rakanalh** [ericdanan/counsel-projectile#18]
Hello,

I am trying to execute `counsel-projectile-ag` but while typing nothing happens and it is stuck at reporting 1 char more while i've typed a bunch of characters.

Please advise

**Comment by ericdanan** [comment]
Hello,

It works for me. Do `projectile-ag` and `counsel-ag` work for you?

**Comment by kain88-de** [comment]
Did you try recompiling ivy/counsel/counsel-projectile? I had a similar issue after upgrading my packages. I think there is a bug in package.el that keeps some packages from recompiling after an upgrade.

**Comment by kain88-de** [comment]
Did you try recompiling ivy/counsel/counsel-projectile? I had a similar issue after upgrading my packages. I think there is a bug in package.el that keeps some packages from recompiling after an upgrade.

**Comment by kain88-de** [comment]
Did you try recompiling ivy/counsel/counsel-projectile? I had a similar issue after upgrading my packages. I think there is a bug in package.el that keeps some packages from recompiling after an upgrade.

**Comment by kain88-de** [comment]
Did you try recompiling ivy/counsel/counsel-projectile? I had a similar issue after upgrading my packages. I think there is a bug in package.el that keeps some packages from recompiling after an upgrade.

**Comment by rakanalh** [comment]
@ericdanan I confirm `counsel-ag` and `projectile-ag` are working fine.

@kain88-de I tried executing `(byte-recompile-directory package-user-dir nil 'force)` with no luck

**Comment by rakanalh** [comment]
@ericdanan I confirm `counsel-ag` and `projectile-ag` are working fine.

@kain88-de I tried executing `(byte-recompile-directory package-user-dir nil 'force)` with no luck

**Comment by ericdanan** [comment]
@kain88-de thanks for the suggestion!

@rakanalh what do you mean by "no luck",  did you get an error or did it just not solve the problem? It is hard for me to understand why you get this strange behavior with `counsel-projectile-ag` but not with `counsel-ag`, since the former basically just passes some options related to ignored files to the latter. Have you tried `counsel-projectile-ag` in different projects (in particular some git and some non-git projects)? Are your packages up-to-date (in particular projectile, counsel, and counsel-projectile)?

**Comment by rakanalh** [comment]
@ericdanan ah sorry, i meant that everything compiled without any issues but `counsel-projectile-ag` didn't work.
I followed your suggestion and tried on a different project, it works. Seems like the cause was because the current project has so many files that ag took some time to look through and delayed display of results. 
I will take a look at how counsel-projectile ignores directories in ag search.

**Comment by ericdanan** [comment]
OK, so if I understand correctly, in this project with a lot of files, `counsel-projectile-ag` actually works but take a lot of time to display the results, is that correct?

What happens if you call `counsel-ag` from the root of this large project, is it faster than `counsel-projectile-ag`? If so I guess that would mean the additional delay comes from handling the ignored files.

**Comment by rakanalh** [comment]
Yes this is correct. 

I tried counsel-ag from the root of my project and it seems like it also takes a while to get back results just like counsel-projectile-ag. However, some query strings are executed faster than others but i guess this is ag specific?

**Comment by ericdanan** [comment]
I'm really not knowledgeable about ag, but it does not seem strange to me that some query string are slower than others. However if `counsel-projectile-ag` is noticeably slower than `counsel-ag` from the same directory and with the same query string, this would suggest to me that either projectile takes a long time identifying the ignored files / directories (`counsel-projectile-ag` just relies on projectile commands to identify them), or ag takes a long time handling them. If the directory is a git project root, then it must be the second option because in that case `counsel-projectile-ag` also leaves the work of identifying ignored files / directories to ag (ag has native support for git).

**Comment by ericdanan** [comment]
Hi @rakanalh , may I close this or are you still facing an issue related to counsel-projectile?

**Comment by rakanalh** [comment]
This issue can be closed, it is mainly because the directory tree had a lot of files to search through.
