### ISSUE TITLE
projectile-switch-project-action cannot be resumed

### ISSUE THREAD

**Issue by DarthFennec** [ericdanan/counsel-projectile#24]
If I use `counsel-projectile-switch-project`, select a project with any action that opens another `ivy` buffer (for example, `counsel-projectile-find-file`), and select a file, I should be able to get back to the file listing using `ivy-resume`. Instead, the minibuffer just says `Selecting deleted buffer`.

**Comment by ericdanan** [comment]
Thank you for pointing this out and sorry for the slow reply. I will look into the issue but I am completely out of time at the moment so it may take a couple of weeks before I can get to it.

**Comment by ericdanan** [comment]
I can reproduce the error. The reason is that `ivy-resume` looks for the buffer `counsel-projectile-find-file` was called from. But `counsel-projectile-switch-project` calls `counsel-projectile-find-file` from a temporary buffer (this is how `projectile-switch-project` works, not specific to counsel-projectile). So the buffer no longer exists when `ivy-resume` is called.

It does not seem straightforward to me how to solve this, I will think about it. But is there any advantage of using `ivy-resume` instead of directly calling `counsel-projectile-find-file` once again?

**Comment by DarthFennec** [comment]
In general, I like to use `ivy-resume` when I already had something typed into the search, and/or I had navigated down the list a decent amount. I'd rather not have to retype/rescroll back to where I was, if I can help it.

For example, if I open a project and do `counsel-projectile-ag`, enter some text I'm looking for, and scroll to a file that appears to be relevant, I'll open the file. If I then realize that this wasn't the file I was looking for after all, I'd like to use `ivy-resume` to continue my search from where I left off, without redoing the entire search.

**Comment by ericdanan** [comment]
I see, will try to make it work.

**Comment by DarthFennec** [comment]
I'm not entirely sure why, but this suddenly appears to work for me now, even though nobody seems to have made any relevant changes recently. Could you verify this?

**Comment by ericdanan** [comment]
I think this is because of recent change in the function `projectile-switch-project-by-name`. This change has other effects, eg if you in a project buffer and switch to another project you should see this buffer incorrectly listed in the project you switched to. There is also a recent issue raised in the projectile repo that is perhaps related. I'd have to take some time to look into this.

**Comment by ericdanan** [comment]
The latest commit introduces a new switching mechanism that should avoid this issue of current buffer being incorrectly listed while still allowing `ivy-resume` to work. Please let me know if it doesn't.
