### ISSUE TITLE
Support for grep/counsel-git-grep

### ISSUE THREAD

**Issue by nickserv** [ericdanan/counsel-projectile#28]
`git grep` is a fast and convenient search tool that comes with git. This package implements similar functionality to `counsel-git` and `counsel-ag` consistently, but it's missing projectile support to mirror `counsel-git-grep`. It would be nice if we could add (or replace) a projectile command to support `git grep`ping through projects instead of using counsel directly. Note that projectile has a built in `projectile-grep` command, which supports `git grep` if you enable `projectile-use-git-grep` (but it unfortunately doesn't use counsel as its `completing-read-function` either way).

**Comment by ericdanan** [comment]
Hi, could you explain a little bit more precisely what you would like to have? It seems to me that if you are inside a git project then `counsel-git-grep` is exactly what you want. Am I missing something?

**Comment by nickserv** [comment]
Sorry for the confusion. My question is more about consistency with other projectile commands than how I can use `git grep` with `counsel`.

`counsel-git-grep` does do have the grepping functionality I want for searching in git repositories. However, I'm used to having this functionality bound to `C-c p s g` and while I could bind it myself, it would be nice if `projectile`'s built in functionality matched this when I have `projectile-use-git-grep` enabled. Additionally, `counsel` doesn't seem to have have a live recursive grep tool that's more generic than `counsel-git-grep` (one that doesn't require a git repo), so it would be nice to be able to use `projectile-grep` as a replacement when I'm in a project that isn't a git repo.

**Comment by ericdanan** [comment]
OK, the easiest thing to do seems to remap `projectile-grep` to a new `counsel-projectile-grep` command that calls `counsel-git-grep` if we are inside a git project and `projectile-use-git-grep` is enabled and falls back to `projectile-grep` otherwise. I will try to do that when I find some time (quite difficult currently), a PR is of course welcome.

Of course it would be better if we could call a counsel "live" `rgrep` command instead of `projectile-grep`, but there does not seem to be one currently. You could ask @abo-abo about that.

Now I am not familiar with these various search command, so I don't really understand why calling `rgrep` is better than calling `grep` with the list of project files. Also I don't know what the difference is with `ag` (there is already a "live" `counsel-ag` command, on which `counsel-projectile-ag` relies, that work for both git and non-git projects). If you have any knowledge about this, I'd be grateful if you could explain.

**Comment by ericdanan** [comment]
It took me while before I got to this, but finally, here is the new command `counsel-projectile-grep'. Please test.

**Comment by ericdanan** [comment]
Please open a new issue if needed.

**Comment by nickserv** [comment]
Thanks! I just tried this out after switching back to using `counsel-projectile` and it seems to be doing everything I'm used to with `counsel-git-grep` (but more consistent with Projectile's UI which is what I was looking for).
