### ISSUE TITLE
Add an action to open project's root directory in dired

### ISSUE THREAD

**Issue by amosbird** [ericdanan/counsel-projectile#58]
Hi, currently I need to use find-file with `.` and `ivy-immediate-done` to achieve this. Do you mind adding such an action? regards.

**Comment by ericdanan** [comment]
I guess you mean a `counsel-projectile-switch-project-action`. I would suggest to instead set `projectile-find-dir-include-top-level` to t, then it is enough to choose the find-directory action and hit `RET` since the project root will be the first candidate.

Now if you prefer adding an action, you can customize the variable `counsel-projectile-switch-project-actions` and add an action with `projectile-dired` as function. Or see the docstring of that variable if you want to do this without using the custom interface.

**Comment by amosbird** [comment]
Thanks!

**Comment by tangxinfa** [comment]
I think open ‘dired’ at the root of the project by default is best when switch project:

     When switch to a new project, it's a big context switch in our brain, 
     instantly ask the user to decide which buffer or file to open in the 
     small ivy buffer let me under lots of pressure.

Custom counsel-projectile-switch-project-action will generate a bunch of `custom-set-variables` codes in .emacs, and not sync with the future versions of counsel-projectile.

And i still don't like set `projectile-find-dir-include-top-level` to `t`, because it le me confusion the project directory hierarchy.

**Comment by tangxinfa** [comment]
I think open ‘dired’ at the root of the project by default is best when switch project:

     When switch to a new project, it's a big context switch in our brain, 
     instantly ask the user to decide which buffer or file to open in the 
     small ivy buffer let me under lots of pressure.

Custom counsel-projectile-switch-project-action will generate a bunch of `custom-set-variables` codes in .emacs, and not sync with the future versions of counsel-projectile.

And i still don't like set `projectile-find-dir-include-top-level` to `t`, because it le me confusion the project directory hierarchy.

**Comment by tangxinfa** [comment]
Following is my hack to open ‘dired’ at the root of the project by default:

    (counsel-projectile-mode 1)
    ;; default to open ‘dired’ at the root of the project, which bind to "."
    (unless (seq-contains (cdr counsel-projectile-switch-project-action) "." `(lambda (elt e) (string-equal elt (car e))))
      (defun my/counsel-projectile-switch-project-action-dired (project)
        "Open ‘dired’ at the root of the project."
        (let ((projectile-switch-project-action
               (lambda ()
                 (projectile-dired))))
          (counsel-projectile-switch-project-by-name project)))
      (setq counsel-projectile-switch-project-action
            (cons
             (car counsel-projectile-switch-project-action)
             (cons
              '("." my/counsel-projectile-switch-project-action-dired "open ‘dired’ at the root of the project")
              (cdr counsel-projectile-switch-project-action)))))

**Comment by ericdanan** [comment]
@tangxinfa your solution seems good to me, but there is now a built-in command `counsel-projectile-modify-action` to modify action lists in various ways. So you could equivalently add the following to your .emacs:

```
(defun my/counsel-projectile-switch-project-action-dired (project)
  "Open ‘dired’ at the root of the project."
  (let ((projectile-switch-project-action
	 (lambda ()
	   (projectile-dired))))
    (counsel-projectile-switch-project-by-name project)))

(counsel-projectile-modify-action
 'counsel-projectile-switch-project-action
 '((add ("." my/counsel-projectile-switch-project-action-dired
	 "open ‘dired’ at the root of the project")
	1)))
```
