### ISSUE TITLE
Change default action of counsel-projectile-switch-project

### ISSUE THREAD

**Issue by DamienCassou** [ericdanan/counsel-projectile#62]
I used to 

```emacs
(setq projectile-switch-project-action #'projectile-vc)
```

to start Magit after selecting a project in projectile. This doesn't seem to work anymore. Instead, I came up with the following workaround:

```emacs
(setcar
     counsel-projectile-switch-project-action
     (1+ (cl-position #'counsel-projectile-switch-project-action-vc
                      (cdr counsel-projectile-switch-project-action)
                      :key #'cadr)))
```

Is that the recommend way? Is there anything simpler?

**Comment by ericdanan** [comment]
Indeed, in the new version `0.2`, `counsel-projectile-switch-project` no longer pays attention to `projectile-switch-project-action`. Since counsel-projectile defines replacements for some projectile commands and also defines new commands that have no projectile counterpart, I find it hard to determine in general what the default action for `counsel-projectile-switch-project` should be based on `projectile-switch-project-action`. So I thought it would be better not to rely on `projectile-switch-project-action` and directly set the actions for `counsel-projectile-switch-project`.

The way you do it seems perfectly fine to me. You could do more simply
```emacs-lisp
(setcar counsel-projectile-switch-project-action 12)
```
but I guess you want something more robust.

It is not completely equivalent to the setup you had previously, because in the previous version the default action for `counsel-projectile-switch-project` (relying on `projectile-switch-project-action`) always had the key <kbd>o</kbd>. So you could call it either with <kbd>RET</kbd> or <kbd>M-o o</kbd>. With your new setup you can call it either with <kbd>RET</kbd> or <kbd>M-o v</kbd>, whereas <kbd>M-o o</kbd> will still call the `counsel-projectile` action (showing project buffers and files).

To obtain the exact same behavior as you had before, you could do something like that:
```emacs-lisp
(setcdr counsel-projectile-switch-project-action
	(append
	 '(("o" counsel-projectile-switch-project-action-vc "open project in vc-dir / magit / monky")
	   (" " counsel-projectile-switch-project-action "jump to a project buffer or file"))
	 (cl-remove-if (lambda (action)
			 (member (cadr action)
				 '(counsel-projectile-switch-project-action-vc
				   counsel-projectile-switch-project-action)))
		       (cdr counsel-projectile-switch-project-action))))
```

Hope this helps. My goal is that all actions (including the default one) be configurable in a simple way, both for users using the Customize interface and those setting things directly (including those using `ivy-set-actions`). But I am not sure I found the best way to go.

**Comment by DamienCassou** [comment]
What about a wrapper around my code? Something like (untested):

```emacs
(defun counsel-projectile-change-default-action (action fn)
  (setcar action (1+ (cl-position fn (cdr action) :key #'cadr)))
```

**Comment by ericdanan** [comment]
Thanks for the suggestion. I a more general function `counsel-projectile-modify-action` that lets you make various modifications to an action list (see its docstring for details).

Your code is now equivalent to:

```emacs-lisp
(counsel-projectile-modify-action
 'counsel-projectile-switch-project-action
 '((default counsel-projectile-switch-project-action-vc)))
```

Alternatively, to obtain the exact same behavior as you had before, you could now do:

```emacs-lisp
(counsel-projectile-modify-action
 'counsel-projectile-switch-project-action
 '((move counsel-projectile-switch-project-action-vc 1)
   (setkey counsel-projectile-switch-project-action-vc "o")
   (setkey counsel-projectile-switch-project-action " ")))
```

Let me know if that's convenient for you.

**Comment by DamienCassou** [comment]
This is perfectly perfect. Thank you very much.

**Comment by ericdanan** [comment]
You are welcome.
