### ISSUE TITLE
counsel-projectile-grep with error code 2

### ISSUE THREAD

**Issue by LuhengStat** [ericdanan/counsel-projectile#69]
I am using counsel-projectile in macOS, sometimes the counsel-projectile-grep results with 
error code 2, but the original projectile-grep can be used. I think this may be a bug of counsel-projectile-grep.

**Comment by ericdanan** [comment]
It's hard to find the issue without more information. Can you post steps to reproduce the error? Do you get the error in git and/or non-git projects?

**Comment by LuhengStat** [comment]
I am not quite sure how this happens. The error just happen with random and I do not know how it happens. Now I have installed ag and change into counsel-projectile-ag instead, and i found this is quite steady and more faster. But I have another question about how to ignore files for counsel-projectile-ag ? Thank you.

**Comment by LuhengStat** [comment]
Thanks, just put a .ignore file in the root. Best

**Comment by sudochop** [comment]
Also running on to this after a fresh install on OSX, all melpa-stable, 26.2. What information could I provide?

**Comment by ericdanan** [comment]
I cannot reproduce the error. Are you calling `counsel-projectile-grep` from a git project and if so what is the value of the variable `projectile-use-git-grep`?

**Comment by sudochop** [comment]
Not in a git project:
`projectile-use-git-grep t` = `error code 2`
`projectile-use-git-grep nil` = `error code 2`
In a git project:
`projectile-use-git-grep t` = works fine
`projectile-use-git-grep nil` = `error code 2`

**Comment by ericdanan** [comment]
Thanks. In a git project with `projectile-use-git-grep t`, `git-grep` is used instead of `grep` and this seems to work fine for you. In all other cases `grep` is used and this seems to be what causes your issue.

Can you try opening a shell from the project root and run `grep` directly with the following command?

```
grep -rnEI PATTERN
```

(I think older versions of `grep` don't support the `-r` switch for recursive search, so perhaps updating `grep` could help.)

**Comment by jonbakke** [comment]
Looks to me like the problem is caused by using BSD grep in a projectile.el project that does not have a known root directory. (Having a .git folder isn't enough to set that for me, though projectile.el appears to recognize that folder correctly.) When ``(eq projectile-project-root nil)``, the argument for ``grep`` does not include a target, so BSD grep expects input from stdin (and therefore returns an error when run without input) while GNU grep does the reasonable thing and recurses the working directory.

My workaround for this on macOS:

1. Install GNU grep. In a terminal:
`brew install grep`
GNU grep will now be available as `ggrep`.

2. Set counsel-projectile to use GNU grep. In Emacs:
`(if (eq system-type 'darwin)
(setq counsel-projectile-grep-base-command "ggrep -rnEI %s -- %%s %s"))`

**Comment by ericdanan** [comment]
Thanks @jonbakke 

@sudochop could you confirm if the error indeed happens to you when `projectile-project-root` is `nil`?

**Comment by ldionmarcil** [comment]
Same occurs with my setup precisely when `projectile-project-root` is null. Seems to happen because the project doesn't get loaded properly, but I'm not sure why it won't load it properly however.

**Comment by david-come-pix4d** [comment]
I have the same issue on emacs 27 (version GNU Emacs 27.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30, cairo version 1.15.10) of 2020-08-12) with counsel-projectile (Version: 20190819.1920 Commit: 7fc4e5d0d65c53edbcb4c25917bcf7faaea36ec7). 

My workaround was to put `(setq projectile-use-git-grep t)` in my config file. It used to work, I don't really know what changed.

**Comment by thatwist** [comment]
If somebody will encounter the same issue - most probably it is related to your default ivy-re-builder being `fuzzy`,
it gets picked up to transform your search query before being supplied to `grep`, the output is not 'pleasant' for grep (though might be ok for ag/rg):
```
(ivy--regex-fuzzy "test")
 "\\(t\\)[^e\n]*\\(e\\)[^s\n]*\\(s\\)[^t\n]*\\(t\\)"
```
while for regex-plus:
```
(ivy--regex-plus "test")
 "test"
```
 You can have explicit override for counsel-projectile-grep:
 ```
 (setq ivy-re-builders-alist
        '(
          ...
          (counsel-projectile-grep . ivy--regex-plus)
          ...
          (t . ivy--regex-fuzzy)))
```
