### ISSUE TITLE
How to use counsel-projectile?

### ISSUE THREAD

**Issue by floli** [ericdanan/counsel-projectile#8]
Hello,

I'm in the process of switching from helm to ivy. I used helm-projectile like that:

```
(use-package helm-projectile
  :ensure t
  :config (progn
    (helm-projectile-on)))
```

Here it seems there is no such thing as `(helm-projectile-on)`.

Do I manually need to set all keybindings to functions that replace projectile function with ivy enhanced ones?

**Comment by ericdanan** [comment]
Hello,

I was working on this and other things. I just updated the master branch. Now you can use `counsel-projcetile-on` to install the keybindings.

Note that there are other changes and I didn't yet update the README:
- The function previously called `counsel-projectile` is now `counsel-projectile-switch-project`, because it does just that.
- There is a new `counsel-projectile` function which is more like `helm-projectile`. If you are not in a project it calls `counsel-projectile-switch-project`. If you are inside a project it instead calls `counsel-projectile-find-file-or-bufffer`, which shows a list of project files and buffers at once (the files that are not currently visited are shown as virtual buffers, as in `ivy-switch-buffer`). From there you can quickly drop to `counsel-projectile-switch-project` with <kbd>M-SPC</kbd>.

`counsel-projectile.el` adds a key binding <kbd>SPC</kbd> for the `counsel-projectile` function in `projectile-command-map` (so you call it with <kbd>C-c p SPC</kbd> by default).

`counsel-projectile-on` does the following:
- Replace key bindings in `projectile-command-map`:
  - <kbd>f</kbd> for `counsel-projectile-find-file`
  - <kbd>d</kbd> for `counsel-projectile-find-dir`
  - <kbd>b</kbd> for `counsel-projectile-find-buffer`
  - <kbd>p</kbd> for `counsel-projectile-switch-project`
- Replace corresponding `projectile-commander` bindings
- If `projectile-switch-project-action` is `projectile-find-file` (the default), change it to `counsel-projectile-find-file-or-buffer`

There is a function `counsel-projectile-off` to undo all that.

Hope it helps, please let me know if you find any issue.

**Comment by ericdanan** [comment]
FYI, I updated the README.

**Comment by floli** [comment]
Great, thanks!
