### ISSUE TITLE
While changing project, it shows only files under /tests/

### ISSUE THREAD

**Issue by zzantares** [ericdanan/counsel-projectile#87]
Hello, I'm experiencing a weird effect, when calling `counsel-projectile-switch-project` and I select the project I want to change to, I'm asked for a file to visit in the project, I want to open let's say... `State.hs`, but when typing `state` I'm only shown the test files (2 of 4 files containing word `state`):

- `StateTTest.hs`
- `StateTest.hs`

While if I use `projectile-switch-project` I'm shown with all files matching the input (in this case 4 files):

- `State.hs`
- `StateT.hs`
- `StateTTest.hs`
- `StateTest.hs`

I've noticed this is the same when switching to other simple projects, where I have only two files `main.go` and `main_test.go`, and when looking for the file, if I input `main` I'm only shown with `main_test.go` but when using `projectile-switch-project` I'm shown all files matching `main`.

Can you help me? perhaps I have a setting turned on that makes this behaviour?

These are the only settings I have with projectile:

```elisp
(setq projectile-globally-ignored-files '(".DS_Store")
          projectile-completion-system 'ivy)
```

Emacs: `GNU Emacs 25.3.1 (x86_64-apple-darwin17.5.0, NS appkit-1561.40 Version 10.13.4 (Build 17E202)) of 2018-05-14`
Projectile Version: `Projectile 0.15.0snapshot`

**Comment by ericdanan** [comment]
That seems strange to me. I created a dummy project with only `main.go` and `main_test.go` and couldn't reproduce your issue. Do you have any specific ivy or counsel setup? Do you still experience this strange behavior if you open of the two files and then call `counsel-projectile-find-file` from there? Can you try with a git and a non-git project?

**Comment by zzantares** [comment]
Hi, I'm sorry for the lack of details. Indeed it's strange, I was finding trouble to find a series of steps to reproduce because when I copied the Haskell project where it happens suddenly stopped to happen, but I think it seems to happen when the git repository is in a non-clean state (with upstaged files).
> Do you have any specific ivy or counsel setup?

Not at all, you can have a look [here](https://github.com/ZzAntares/.emacs.d/blob/master/init.el#L585), counsel settings are right below ivy settings.

> Do you still experience this strange behavior if you open of the two files and then call counsel-projectile-find-file from there?

No, that works just fine, it only happens while switching projects.

> Can you try with a git and a non-git project?

Initially I thought it was happening when git is in a non clean state, but then after removing the `.git` is still happening and more over the amount of files suggested reduces drastically when it's not a git repo.

### Steps to reproduce

[Here is a simple go project](https://github.com/ZzAntares/selectormetodologias) where I'm having this effect. Please don't mind the wrong go code folder structure.

1. `git clone git@github.com:ZzAntares/selectormetodologias.git`
2. `touch selectormetodologias/api/src/main_test.go`
3. Visit project in Emacs so it's saved to the projectile known projects.
4. Close all buffers related to the project, then re-open with `counsel-projectile-switch-project`.
5. Select the recently cloned project.
5. Type `main` it should list:

```
api/src/main_test.go
api/src/main.go
app/src/Main.elm
app/src/Main.css
```

But instead shows:

```
api/src/main_test.go
app/src/Main.elm
app/src/Main.css
```

If instead you use `projectile-switch-project` it will show all the correct files.

### Further evidence

1. Close all buffers related to the project.
2. `rm -rf selectormetodologias/.git`
3. `M-x projectile-remove-known-project`
4. Visit project in Emacs so it's saved to the projectile known projects.
5. Close all buffers related to the project, then re-open with `counsel-projectile-switch-project`.
6. Select the recently added project.
7. At this point to me only shows 4 files.
5. Type `main` and it doesn't match any file.

If instead you use `projectile-switch-project` it works fine.

Uff, those steps took some time to write :tired_face:, can you reproduce it?

**Comment by ericdanan** [comment]
Thanks for the detailed report. I couldn't reproduce the issue at first, but it turns out I hadn't updated ivy for a couple of weeks, and now I updated it I do observe the same behavior as you.

The change in ivy that triggered this issue in counsel-projectile is a fix for a bug with sorting in ivy: when there was no entry for the current command in `ivy-sort-functions-alist`, the default `t` entry in this list was not used as it should so no sorting was happening, now it does. Since counsel-projectile adds entries for several commands, including `counsel-projectile`, in `ivy-sort-functions-alist` so as to have no sorting, there shouldn't have been any effect in counsel-projectile with the default settings. But it turns I had not implemented this correctly (I should have used the collection function and not the caller in the added entries), so it had no effect and the change in ivy triggered the default sorting for the counsel-projectile commands. And it turns out there is also an issue in ivy when sorting for collection functions, which caused the strange behavior in `counsel-projectile-switch-to-buffer` and `counsel-projectile` (but not `counsel-projectile-find-file` because it does not use a collection function).

I just pushed a commit to fix the default sorting in counsel-projectile. So the bottom line is that if you update counsel-projectile and stick to the default settings, the issue should be solved. If you modify `ivy-sort-functions-alist` so as to have sorting in `counsel-projectile` or `counsel-projectile-switch-to-buffer`, then you may still have issues. I submitted a PR in ivy to fix sorting for collection functions, see abo-abo/swiper/pull/1592.

Let me know if at least the default settings work for you now.

**Comment by ericdanan** [comment]
With the latest commits to both ivy and counsel-projectile, it should now work properly whether you sort candidates or not. Note that I slightly changed the way to customize sorting (see the README).

Please reopen if you still hav issues.
