### ISSUE TITLE
Bindings in `counsel-projectile-map` no longer work

### ISSUE THREAD

**Issue by cmacrae** [ericdanan/counsel-projectile#97]
Hi @ericdanan 👋   

Thanks for `counsel-projectile`!  

I just updated my version to `20180822.1458` on melpa and I seem to be hitting an issue.  
This was the configuration I was using:  
```elisp
    (use-package counsel-projectile
        :bind
        ("C-c p s r" . counsel-projectile-rg)
          (:map counsel-projectile-mode-map
          ("C-c p p" . projectile-persp-switch-project))
        :init
        (counsel-projectile-mode))

```

With the update; `counsel-projectile-mode-map` was no longer valid.  
I assumed this was now `counsel-projectile-map`, so set it accordingly:  
```elisp
    (use-package counsel-projectile
        :bind
        ("C-c p s r" . counsel-projectile-rg)
          (:map counsel-projectile-map
          ("C-c p p" . projectile-persp-switch-project))
        :init
        (counsel-projectile-mode))
```

However, I now find that when trying to initiate a project switch with `C-c p p`, it's undefined.  
Any ideas why this is happening?

**Comment by ericdanan** [comment]
Hi

Indeed `counsel-projectile-mode-map` and `counsel-projectile-command-map` were recently removed. The standard projectile keymaps (`projectile-mode-map` and `projectile-command-map`) are now directly used instead. See the upgrading section of the README. `counsel-projectile-map` is a minibuffer keymap for the command `counsel-projectile`,  so not related to this.

In addition, the `counsel-projectile-rg` keyginding is no longer needed, because projectile now binds `C-c p r` to `projectile-ripgrep` and counsel-projectile automatically remaps this to `counsel-projectile-rg`.

So the following should now work for you (it will make the binding available in projectile, even if you don't turn on `counsel-projectile-mode`):
```emacs-lisp
    (use-package counsel-projectile
        :bind
        ((:map projectile-mode-map
          ("C-c p p" . projectile-persp-switch-project))
        :init
        (counsel-projectile-mode))
```

Or alternatively:
```emacs-lisp
    (use-package counsel-projectile
        :bind
        ((:map projectile-command-map
          ("p" . projectile-persp-switch-project))
        :init
        (counsel-projectile-mode))
```

**Comment by cmacrae** [comment]
Perfect! That's sorted it. Thanks for the fast response, thorough explanation, and examples.  
Much appreciated 👍
