### ISSUE TITLE
Replacing counsel-projectile-command-map

### ISSUE THREAD

**Issue by Opioid** [ericdanan/counsel-projectile#99]
I used to have the following configuration in order to use counsel-projectile-rg "by default":

    (define-key counsel-projectile-command-map (kbd "s") 'counsel-projectile-rg)

Can the behavior still be achieved after the changes in version 0.3?

**Comment by ericdanan** [comment]
Sure. Counsel-projectile now relies directly on `projectile-command-map` instead of `counsel-projectile-command-map`. Also, projectile now has a `projectile-ripgrep` command that `counsel-projectile-mode` remaps to `counsel-projectile-rg`. The default key binding for this command is `C-c p r g`. You can change it with:

```el
(define-key projectile-command-map (kbd "s") 'projectile-ripgrep)
```

**Comment by Opioid** [comment]
Thank you!
